#this took me 15 minutes, i had to copy every. single. fuckin. character. from a unicode table


text = input("ples input teh shit u wanna ecbuhoifuy")
echoified = (text
    .replace("A", "𝐀")
    .replace("B", "𝐁")
    .replace("C", "𝐂")
    .replace("D", "𝐃")
    .replace("E", "𝐄")
    .replace("F", "𝐅")
    .replace("G", "𝐆")
    .replace("H", "𝐇")
    .replace("I", "𝐈")
    .replace("G", "𝐉")
    .replace("K", "𝐊")
    .replace("L", "𝐋")
    .replace("M", "𝐌")
    .replace("N", "𝐍")
    .replace("O", "𝐎")
    .replace("P", "𝐏")
    .replace("Q", "𝐐")
    .replace("R", "𝐑")
    .replace("S", "𝐒")
    .replace("T", "𝐓")
    .replace("U", "𝐔")
    .replace("V", "𝐕")
    .replace("W", "𝐖")
    .replace("X", "𝐗")
    .replace("Y", "𝐘")
    .replace("Z", "𝐙")
    #smolcaps
    .replace("a", "𝐚")
    .replace("b", "𝐛")
    .replace("c", "𝐜")
    .replace("d", "𝐝")
    .replace("e", "𝐞")
    .replace("f", "𝐟")
    .replace("g", "𝐠")
    .replace("h", "𝐡")
    .replace("i", "𝐢")
    .replace("j", "𝐣")
    .replace("k", "𝐤")
    .replace("l", "𝐥")
    .replace("m", "𝐦")
    .replace("n", "𝐧")
    .replace("o", "𝐨")
    .replace("p", "𝐩")
    .replace("q", "𝐪")
    .replace("r", "𝐫")
    .replace("s", "𝐬")
    .replace("t", "𝐭")
    .replace("u", "𝐮")
    .replace("v", "𝐯")
    .replace("w", "𝐰")
    .replace("x", "𝐱")
    .replace("y", "𝐲")
    .replace("z", "𝐳")
    )


print(echoified)

